services:
  - type: web
    name: stock-average-calculator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app --bind 0.0.0.0:$PORT
    plan: free
    healthCheckPath: /

